branches:
  only:
    - source
language: node_js
node_js:
  - "0.10"
script:
  - "npm install -g hexo"
  - "npm install"
  - "hexo generate --debug"
after_success:
  - "git clone $DEPLOY_REPO git_deploy"
  - "rm -r git_deploy/*"
  - "cp -r public/* git_deploy"
  - "cd git_deploy"
  - "git config --global push.default simple"
  - "git config --global user.name 'zhiyue'"
  - "git config --global user.email cszhiyue@gmail.com"
  - "git add -A"
  - "git commit -m 'Site updated'"
  - "git push -q"
